//! Render conformance against libiamf's rendered reference WAVs (fetch
//! with tools/fetch_vectors.sh; missing files fail the run unless
//! IAMF_VECTORS_OPTIONAL=1 downgrades them to skips).
//!
//! Same-layout rendering is bit-exact. Cross-layout rendering is allowed a
//! small LSB tolerance: the references are generated by iamf-tools, whose
//! renderer arithmetic differs from libiamf's f32 tables at the last bit.

mod common;

use common::vectors_dir;
use iamf_codecs::DefaultFactory;
use iamf_dec::layout::SoundSystem;
use iamf_dec::presentation::{Descriptors, PresentationDecoder};
use iamf_obu::ObuIter;

/// Minimal 16-bit PCM RIFF reader.
fn read_wav_s16(path: &std::path::Path) -> Option<(u16, Vec<i16>)> {
    let data = std::fs::read(path).ok()?;
    if &data[..4] != b"RIFF" || &data[8..12] != b"WAVE" {
        return None;
    }
    let mut pos = 12;
    let mut channels = 0u16;
    while pos + 8 <= data.len() {
        let id = &data[pos..pos + 4];
        let size = u32::from_le_bytes(data[pos + 4..pos + 8].try_into().unwrap()) as usize;
        let body = &data[pos + 8..(pos + 8 + size).min(data.len())];
        match id {
            b"fmt " => channels = u16::from_le_bytes(body[2..4].try_into().unwrap()),
            b"data" => {
                let samples = body
                    .chunks_exact(2)
                    .map(|b| i16::from_le_bytes([b[0], b[1]]))
                    .collect();
                return Some((channels, samples));
            }
            _ => {}
        }
        pos += 8 + size + (size & 1);
    }
    None
}

use iamf_dec::post::quantize_s16 as quantize;

fn render_case(vector: &str, layout_index: usize, sound_system: u8, tolerance: i32) {
    let dir = vectors_dir();
    let iamf_path = dir.join(format!("{vector}.iamf"));
    let ref_path = dir.join(format!(
        "{vector}_rendered_id_42_sub_mix_0_layout_{layout_index}.wav"
    ));
    let files = std::fs::read(&iamf_path).ok().zip(read_wav_s16(&ref_path));
    let (data, (ref_channels, reference)) =
        require_vectors!(files, format_args!("{vector} + rendered reference"));

    let descriptors = Descriptors::collect(&data).unwrap();
    let target = SoundSystem::from_u8(sound_system).unwrap();
    let mut decoder = PresentationDecoder::new(&descriptors, 0, target, &DefaultFactory).unwrap();
    for obu in ObuIter::new(&data).map(Result::unwrap) {
        decoder.process_obu(&obu).unwrap();
    }
    let mix = decoder.finish().unwrap();

    assert_eq!(
        mix.channels,
        usize::from(ref_channels),
        "{vector}: channel count"
    );
    let ours: Vec<i16> = mix.interleaved.iter().map(|&s| quantize(s)).collect();
    assert_eq!(ours.len(), reference.len(), "{vector}: sample count");
    let max_diff = ours
        .iter()
        .zip(&reference)
        .map(|(&a, &b)| (i32::from(a) - i32::from(b)).abs())
        .max()
        .unwrap_or(0);
    assert!(
        max_diff <= tolerance,
        "{vector}: max diff {max_diff} exceeds tolerance {tolerance}"
    );
}

#[test]
fn stereo_passthrough_bit_exact() {
    render_case("test_000002", 0, 0, 0);
}

#[test]
fn foa_to_stereo() {
    render_case("test_000038", 0, 0, 1);
}

#[test]
fn surround_714_passthrough_bit_exact() {
    render_case("test_000070", 2, 9, 0);
}

#[test]
fn surround_714_to_stereo() {
    render_case("test_000070", 0, 0, 1);
}

#[test]
fn surround_714_to_712() {
    render_case("test_000070", 1, 10, 3);
}

#[test]
fn surround_512_to_stereo() {
    render_case("test_000069", 0, 0, 1);
}

#[test]
fn scalable_stereo_layer_bit_exact() {
    render_case("test_000036", 0, 0, 0);
}

#[test]
fn scalable_demixed_51() {
    render_case("test_000036", 1, 1, 1);
}

#[test]
fn multi_element_scalable_to_stereo() {
    render_case("test_000086", 0, 0, 1);
}

#[test]
fn multi_element_scalable_to_312() {
    render_case("test_000086", 1, 11, 1);
}

#[test]
fn multi_element_scalable_demixed_512() {
    render_case("test_000086", 2, 2, 1);
}

#[test]
fn animated_linear_mix_gain() {
    render_case("test_000065", 0, 0, 1);
}

#[test]
fn animated_bezier_mix_gain() {
    // Bezier time-parameterization differs numerically from the
    // iamf-tools reference renderer (max observed 23 LSB, about -63 dBFS).
    render_case("test_000066", 0, 0, 32);
}

#[test]
fn animated_step_linear_bezier_16k() {
    render_case("test_000088", 0, 0, 1);
}

#[test]
fn flac_scalable_stereo_layer_bit_exact() {
    render_case("test_000073", 0, 0, 0);
}

#[test]
fn flac_scalable_demixed_51() {
    render_case("test_000073", 1, 1, 1);
}

/// AAC is lossy and the reference is rendered from the original PCM, so
/// only coding-noise-level closeness is asserted.
#[test]
fn aac_stereo_decodes() {
    render_case("test_000090", 0, 0, 512);
}

/// Ambisonics PROJECTION mode: decoded substreams through the Q1.15
/// demixing matrix (near-identity, LPCM).
#[test]
fn projection_foa_to_stereo() {
    render_case("test_000042", 0, 0, 1);
}

/// PROJECTION with coupled Opus substreams. Like the AAC case, the
/// reference is rendered from the pre-codec PCM, so the tolerance covers
/// Opus coding noise (observed max 2839, ~18 dB SNR at 0.99 correlation);
/// a channel-mapping or matrix bug would far exceed it.
#[test]
fn projection_opus_coupled_to_stereo() {
    render_case("test_000048", 0, 0, 3000);
}

/// No reference WAVs exist for sound systems E–H and 9.1.6, so assert
/// shape and sanity: correct channel count, same duration as the stereo
/// render, all samples finite, output not silent.
/// Expanded loudspeaker layouts (§3.6.2): whole (9.1.6, 7.1.5.4,
/// 10.2.9.3) and as subsets of their reference layout, rendered through
/// the reference layout's matrices (OAR). One per reference layout.
#[test]
fn expanded_916_and_stereo_tb_to_714() {
    render_case("test_000608", 1, 9, 1);
}

#[test]
fn expanded_bottom_3ch_of_10293_to_712() {
    render_case("test_000829", 1, 10, 1);
}

#[test]
fn expanded_top_1ch_of_7154_to_stereo() {
    render_case("test_000831", 0, 0, 1);
}

#[test]
fn expanded_7154_to_714() {
    render_case("test_000833", 1, 9, 1);
}

#[test]
fn expanded_10293_to_71() {
    render_case("test_001014", 1, 8, 1);
}

#[test]
fn extended_sound_systems_render_sanely() {
    let data = require_vectors!(
        std::fs::read(vectors_dir().join("test_000070.iamf")).ok(),
        "test_000070"
    );
    let render = |sound_system: u8| {
        let descriptors = Descriptors::collect(&data).unwrap();
        let target = SoundSystem::from_u8(sound_system).unwrap();
        let mut decoder =
            PresentationDecoder::new(&descriptors, 0, target, &DefaultFactory).unwrap();
        for obu in ObuIter::new(&data).map(Result::unwrap) {
            decoder.process_obu(&obu).unwrap();
        }
        decoder.finish().unwrap()
    };
    let stereo = render(0);
    let frames = stereo.interleaved.len() / stereo.channels;
    // E (4+5+1), F (3+7+0), G (4+9+0), H (9+10+3), 9.1.6.
    for (sound_system, channels) in [(4u8, 11usize), (5, 12), (6, 14), (7, 24), (13, 16)] {
        let mix = render(sound_system);
        assert_eq!(mix.channels, channels, "sound system {sound_system}");
        assert_eq!(
            mix.interleaved.len(),
            frames * channels,
            "sound system {sound_system}: duration"
        );
        assert!(
            mix.interleaved.iter().all(|s| s.is_finite()),
            "sound system {sound_system}: non-finite samples"
        );
        assert!(
            mix.interleaved.iter().any(|&s| s.abs() > 1e-4),
            "sound system {sound_system}: silent output"
        );
    }
}

/// Binaural (output layout 14) currently uses the same gain matrices as
/// the stereo render — libiamf-without-binauralizer behavior — so the two
/// must match exactly.
#[test]
fn binaural_matches_stereo_fallback() {
    let dir = vectors_dir();
    for vector in ["test_000070", "test_000038", "test_000086"] {
        let data = require_vectors!(
            std::fs::read(dir.join(format!("{vector}.iamf"))).ok(),
            format_args!("{vector}")
        );
        let render = |sound_system: u8| {
            let descriptors = Descriptors::collect(&data).unwrap();
            let target = SoundSystem::from_u8(sound_system).unwrap();
            let mut decoder =
                PresentationDecoder::new(&descriptors, 0, target, &DefaultFactory).unwrap();
            for obu in ObuIter::new(&data).map(Result::unwrap) {
                decoder.process_obu(&obu).unwrap();
            }
            decoder.finish().unwrap().interleaved
        };
        assert_eq!(render(14), render(0), "{vector}: binaural != stereo");
    }
}
